name: refine-app

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push container image to registry
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: travis99/refine-admin:latest
          file: ./Dockerfile
  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      CI_DEPLOY_ENV_VARS: ${{ secrets.CI_DEPLOY_ENV_VARS }}
      CI_DEPLOY_PRIVATE_KEY: ${{ secrets.CI_DEPLOY_PRIVATE_KEY }}
      CI_DEPLOY_SERVER: ${{ secrets.CI_DEPLOY_SERVER }}
      CI_REGISTRY_USER: ${{ vars.DOCKER_HUB_USERNAME }}
      CI_REGISTRY_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
      CI_DEPLOY_IMAGE: travis99/refine-admin:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Set deploy key
      #   run: echo "${{ secrets.CI_DEPLOY_PRIVATE_KEY }}" | tr -d '\r' > $CI_DEPLOY_PRIVATE_KEY
      - name: Deploy the app
        uses: digitalocean/app_action/deploy@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          script: |
            ls
  notification:
    runs-on: ubuntu-latest
    env:
      BUILD_FAIL: ${{ (needs.build.result == 'failure' || needs.build.result == 'timed_out') || (needs.deploy.result == 'failure' || needs.deploy.result == 'timed_out') }}
    needs:
      - build
      - deploy
    if: ${{ always() || (needs.build.result == 'failure' || needs.build.result == 'timed_out') || (needs.deploy.result == 'failure' || needs.deploy.result == 'timed_out') }}
    steps:
      - name: Check version
        uses: actions/checkout@v4
      - name: Print var
        run: echo $BUILD_FAIL
      - name: List folder
        run: ls
      - name: Run noti script
        run: |
          bash ./deploy/scripts/notification.sh
