name: refine-app

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push container image to registry
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: travis99/${{ github.repository }}:latest
          file: ./Dockerfile
  notification:
    runs-on: ubuntu-latest
    env:
      BUILD_FAIL: ${{ (needs.build.result == 'failure' || needs.build.result == 'timed_out') }}
    needs:
      - build
    if: ${{ always() || (needs.build.result == 'failure' || needs.build.result == 'timed_out') }}
    steps:
      - name: Check version
        uses: actions/checkout@v4
      - name: Print var
        run: echo $BUILD_FAIL
      - name: List folder
        run: ls
      - name: Run noti script
        run: |
          bash ./deploy/scripts/notification.sh
